apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: mohamed710/solar-system-gitea:b9f829d863afec894b2924847336d1aec9379ff8
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
