apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: mohamed710/solar-system-gitea:9e9ebfa482ea2d9cc30483d3ab3909206b5183b2
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 3000
