apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: mohamed710/solar-system-gitea:0a8c210bd751b3915a6db29249962a5968c60834
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 3000
