apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: mohamed710/solar-system-gitea:192a9b5c22eea8bce86caf9d9086fc8d7b3753e0
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 3000
