apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: mohamed710/solar-system-gitea:271fc354dcbd44f4f6b391da59858a152e695509
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
